collections:
  default:
    output: true

  elements:
  permalink: /elements/:title/
  directory: "_elements"  


title: GeamiGeami Science
description: Science Page


url: "https://gaemigaemi.github.io/science/" 


plugins:
  - jekyll-feed
  - jekyll-seo-tag